version: "3"
services:
    tabby:
        build: .
        restart: always
        depends_on:
        - db
        ports:
        - 9090:80
        volumes:
        - ./app-dist:/app-dist
        environment:
        - DATABASE_URL=mysql://root:123@db/tabby
        - PORT=80
        - ENABLE_HOMEPAGE=False
        - DEBUG=False
        - APP_DIST_STORAGE=file:///app-dist
        - WAIT_HOSTS=db:3306

    db:
        image: mariadb:10.7.1
        restart: always
        environment:
            MARIADB_DATABASE: tabby
            MARIADB_USER: user
            MARIADB_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123
